services:
  postgres:
    image: postgres:16
    container_name: oitassist-db
    environment:
      POSTGRES_DB: oitassist
      POSTGRES_USER: ${DATASOURCE_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/ita-social-projects/oitassist/build:latest
    container_name: oitassist-backend
    depends_on:
      - postgres
    ports:
      - "80:80"
    env_file:
      - environment.env

volumes:
  postgres_data:
