##################################
####### Profile Default ##########
##################################
server.port=8080

spring.profiles.active=${PROFILE}

spring.datasource.url=jdbc:postgresql://localhost:5432/oitassist
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.drop-first=false

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.properties.hibernate.jdbc.batch_size=10

########## Hardest example
oit.count=42
oit.price=19.92
oit.enabled=true
oit.value=
oit.value2=
oit.colors=red,green,blue
oit.colors2[0]=red
oit.colors2[1]=green
oit.colors2[2]=blue
oit.routes[0].path=/api/*
oit.routes[0].methods[0]=GET
oit.routes[0].methods[1]=POST
oit.routes[1].path=/admin
oit.person.name=Olexandr
oit.person.age=30
oit.description=First Line\nSecond Line
oit.message=this is a long message, that will be collapsed into a single line
oit.number=123
oit.code=007
oit.timeout=150m
oit.cache=45s
oit.created=2025-01-15
oit.event=2025-03-20T14:30:00Z


###############################
#application.properties # default
#application-dev.properties # dev
#application-stage.properties # stage
#application-prod.properties # prod
###############################
# IMPOSIBLE to make several profiles in single file

################################
######## Profile Dev ###########
################################
spring.config.activate.on-profile=dev

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver=${DATASOURCE_DRIVER}

spring.liquibase.enabled=${LIQUIBASE_ENABLED}
spring.liquibase.change-log=${LIQUIBASE_CHANGE_LOG}

spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:validate}


################################
######## Profile Stage #########
################################
spring.config.activate.on-profile=stage

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver=${DATASOURCE_DRIVER}

spring.liquibase.enabled=${LIQUIBASE_ENABLED}
spring.liquibase.change-log=${LIQUIBASE_CHANGE_LOG}

spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:validate}


################################
######## Profile Prod ##########
################################
spring.config.activate.on-profile=prod